#%RAML 1.0 Library
usage: Common datatypes and traits for Flight Reservation API

types:
  Money: !include ../dataTypes/money.raml
  Flight: !include ../dataTypes/flight.raml
  Reservation: !include ../dataTypes/reservation.raml
  Passenger: !include ../dataTypes/passenger.raml
  ErrorResponse: !include ../dataTypes/errorResponse.raml
