#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example: { "error": "Bad request" }
  404:
    body:
      application/json:
        example: { "error": "Not found" }
  500:
    body:
      application/json:
        example: { "error": "Internal server error" }
